AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  markChoreComplete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::439188974788:role/service-role/markChoreComplete-role-bichv02b
      Environment:
        Variables:
          DRONE_COMMIT: 200d818207c542e4773ddcde49d1fc595eed0a40
